apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: account-service-v2-timeout
spec:
  destination:
    name: account-service
  precedence: 7
  match:
    request:
      headers:
        x-version: 
          exact: "v2"
  route:
  - labels:
      version: v2
  httpReqTimeout:
    simpleTimeout:
      timeout: 1s      
