apiVersion: config.istio.io/v1beta1
kind: DestinationPolicy
metadata:
  name: accounts-v2-circuit-breaker
spec:
  destination:
    name: account-service
    labels:
      version: v2
  circuitBreaker:
    simpleCb:
      sleepWindow: 15s
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 50
      httpConsecutiveErrors: 1
