apiVersion: config.istio.io/v1beta1
kind: DestinationPolicy
metadata:
  name: accounts-v2-circuit-breaker
spec:
  destination:
    name: account-service
    labels:
      version: v2
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      sleepWindow: 1m
      httpConsecutiveErrors: 1
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 50 
      httpMaxRequestsPerConnection: 1
