apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: accounts-v1-v2-headerv1
  namespace: default
spec:
  destination:
    name: account-service
  precedence: 10
  match:
    request:
      headers:
        x-version: 
          exact: "v1"
  route:
  - labels:
      version: v1
    weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: accounts-v1-v2-headerv2
  namespace: default
spec:
  destination:
    name: account-service
  precedence: 9
  match:
    request:
      headers:
        x-version: 
          exact: "v2"
  route:
  - labels:
      version: v2
    weight: 100
