apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: accounts-v1-v2
  namespace: default
spec:
  destination:
    name: account-service
  precedence: 5
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
