server:  
  port: ${PORT:3333}

spring:
  data:
    mongodb:
      host: ${MONGODB_SERVICE_SERVICE_HOST:localhost}
      port: ${MONGODB_SERVICE_SERVICE_PORT:27017}
      
#eureka:  
#  client:
#    serviceUrl:
#      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: false
    
feign:
  hystrix:
    enabled: false