kind: Service
apiVersion: v1
metadata:
  name: account-service
spec:
  selector:
    run: account-service
  ports:
    - port: 2222
      protocol: TCP
      targetPort: 2222
      nodePort: 30222
  type: NodePort

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: account-service
    spec:
      containers:
      - name: account-service
        image: account-service:1.0
        ports:
        - containerPort: 2222
          protocol: TCP

